# Registry URL
- type: replace
  path: /instance_groups/name=registry/jobs/name=registry/properties/registry/http/host?
  value: https://registry.((system_domain))

- type: replace
  path: /instance_groups/name=harbor/jobs/name=adminserver/properties/adminserver/docker_registry_url?
  value: https://registry.((system_domain))

# Harbor URL
- type: replace
  path: /instance_groups/name=registry/jobs/name=registry/properties/registry/auth/token/realm?
  value: https://harbor.((system_domain))/service/token

- type: replace
  path: /instance_groups/name=harbor/jobs/name=adminserver/properties/adminserver/external_url?
  value: https://harbor.((system_domain))

# Route Registrar
- type: replace
  path: /instance_groups/name=nginx/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: cf
    properties:
      route_registrar:
        routes:
          - name: registry
            registration_interval: 20s
            port: 80
            uris:
              - registry.((system_domain))
          - name: harbor
            registration_interval: 20s
            port: 80
            uris:
              - harbor.((system_domain))

# Releases
- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.159.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.159.0
    sha1: 739f663f976fea826595880cfd58470bc8d49172
