# Add external URL property to adminserver
- type: replace
  path: /instance_groups/name=harbor/jobs/name=adminserver/properties/adminserver/external_url?
  value: https://harbor.((system_domain))

# Add route registrar to nginx job
- type: replace
  path: /instance_groups/name=nginx/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: cf
    properties:
      route_registrar:
        routes:
          - name: harbor
            registration_interval: 20s
            port: 80
            uris:
              - harbor.((system_domain))

# Add routing release
- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.159.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.159.0
    sha1: 739f663f976fea826595880cfd58470bc8d49172
